.\"Man page for builder, by Dave Henderson.
.TH builder 1 "2026 March 25"
.SH NAME
\fIbuilder\fR - package builder




.SH SYNOPSIS

.B builder [OPTIONS] ACTION NAME

ACTIONS:
  -b   build a distributable package
  -c   compile the software only, no packaging
  -d   download the builder profile (uses URL_REPO)
  -i   install the builder profile
  -p   create a builder profile
  -r   only re-package software instead of building
  -t   create a package template: info, profile

  --help      shows this screen
  --version   displays the software version

OPTIONS:
  -A   the CPU architecture to build: a32,a64,i32,i64,r32,r64,all (default)
  -C   obtain source code from:
          dev(eloper)|dir(ectory)|git(clone)|(distro)repo
  -D   package using directories in DIR_DUMP instead of NAME value
  -F   skips packaging until final pass
  -I   download the package info file and use its locations
  -M   the compile type to use:
          autoconf
          autogen
          bootstrap
          cmake
          custom
          default (configure, make, make install)
          scons
  -N   the number of passes to make when compiling
  -P   prevent patching from occurring
  -R   remove a portion of NAME when packaging; can use regex anchors
  -S   package all contents in a single package - do NOT separate
  -U   do not unload compilation packages afterwards




.SH TOC

1.  DESCRIPTION
2.  CONFIGS
3.  PARAMETERS
4.  ACTIONS
5.  OPTIONS
6.  INFO FILE
7.  EXAMPLES
8.  BUGS
9.  COPYRIGHT
10. AUTHORS




.SH DESCRIPTION

.I builder
was created to not only make it easier to compile software, but to also
enable a quick way to distribute the means of doing so. Imagine having a
very small file that contains the dependencies and instructions required
to compile (for various CPU architectures), one or more places to obtain
the source code, any desired patches, and any additional files to include
in an installation (e.g. desktop files). That file, which is known as a
"builder profile", can be parsed by builder to automatically carry out
each of those steps, with an optional final process of creating packages
for distribution - making this suitable for normal end users and package
maintainers alike! By simply making the builder profile available, anyone
can quickly and effortlessly compile any software by issuing a single,
short command!

[package maintainers]
It is important to note that this software will not magically determine
all of the steps outlined above and do it for you. Someone has to actually
outline this process in an initial builder profile (ideally being the
software developer). This project is meant to provide an easy way to use
the contributions of others who have taken those steps, and allow package
maintainers of each distro to quickly tweak the profile to fit their own
system. This makes it trivial to modify the compile parameters, add or
remove patches, add or remove graphics, include GUI desktop files, and
other items to specifically tailor a software build.

[software developers]
Builder works with a variety of popular methods of compilation including
autoconf, autogen, bootstrap, cmake, scons, and a default (configure,
make, make install). There is even an option to create a custom method if
you require it. This allows you the freedom to choose which one will work
best for you and your project.

While builder does not make any stage of development easier for you, its
main design goal is to make it VERY easy for an end user to compile your
software, or aid in the rapid distribution of your project to qualified
package maintainers of the various Linux distros. By constructing a
(generic) builder profile for your work, you are helping to streamline
the steps necessary for them to tailor your software to their specific
environment. We would encourage any developer to include this as a zip or
tarball packaged with their source code, or at least an option to download
from their website.




.SH CONFIGS

There are several configuration files that are used with builder. The main
file is used to define global variable and default profile values, and is
typically located in '/etc/builder'. To provide flexibility, there are
three additional directories that are permissible. Each can exist and also
modify the values: '/usr/local/etc/builder', '~/.etc/builder' (XSB), and
'~/.builder' (LSB). None of these variables can be adjusted using passed
values to builder.

The other configuration file is included in each builder profile. There
are some overlaping of values as stated above, but also several that are
unique. Unlike the global config, there is only one place that this file
can be stored - the root of the profile. However, this file can utilize
a numeric extension to designate different values depending on the number
of passes a software needs to be fully compiled. This extension needs to
correspond with the pass. So, if a single pass is required, the filename
should remain as 'config' with no extension. If a software requires two or
more passes, there should be an equal number of files using the naming
convention 'config.1', 'config.2', etc, each with their own configuration
definitions that correspond to the pass number. None of these variables
can be adjusted using passed values to builder.

While not a configuration file, there is one other file that needs to be
discussed. This file also would reside alongside the 'config' in each
builder profile, and is named 'params'. Like its associated 'config', this
file can also have numeric file extensions for multi-pass profiles. Unlike
the 'config' files, there can be a 'params' file without a numeric suffix
for common values when used in a multi-pass profile. The function of this
file is to define the parameter values that should be passed to builder
when building software. This will prevent mistakes by end users who would
not know what values to pass. For example, if the software required two
passes, instead of informing every end user to pass '-N 2', you can simply
add a 'PASS=2' value in this file and builder will acknowledge that for
the absence of the passed parameter.

To summarize:
  o The global config search order:
    /etc/builder, /usr/local/etc/builder, ~/.etc/builder, ~/.builder
  o The profile config naming convention:
    config[.1, .2, ...]
    params[.1, .2, ...]

Before explaining each variable in detail, it is important to note that
some of these values can contain variables themselves (if desired). Those
that fall within this scope must have their value enclosed with single
quotes (') as they are interprited at specific times of execution instead
of the initial loading of the script. The variables for use are:
  ${PACKAGE} - adjusted package name with NAME_SFX (only when packaging)
  ${NAME} - package name
  ${ARCH} - devices' CPU architecture
  ${TYPE} - package type (e.g. bin, doc, lib, etc)
  ${PASS} - current pass number
We will now cover each variable available for adjustment in the config
files, noting when any of the above variables can be utilized.




.I Global Config

.B DEBUG
To see the commands that take place while builder is being executed, set
this value to 1. The log will then contain that additional information.


.B DIR_DUMP
As the name suggests, this is the staging area that is used to dump the
compiled program into before making the (various) package(s) for
distribution.

.B DIR_INST
Similar to the PREFIX value when compiling, this value allows a directory
structure to be injected into the overall path where the compiled software
will reside. In an LSB environment, this value will be '/usr/local' for
everything that i's not part of the OS. If using XSB, then this value will
remain blank since packages can be installed in multiple locations, each
mirroring the same directory structure.

.B DIR_PROF
This variable stores the location of the builder profiles, and should NOT
include the NAME variable as part of its value.

.B DIR_REPO
If the user elects to create distributable packages (using the -b action),
then this directory is used to store those generated files. This directory
is also used when passing '-C dir' as the location where the source code
currently resides.

.B DIR_TEMP
The directory that is used for temporary files created during the building
process.


.B DEP_MAKE_ALL
There are always packages that need to be installed in order to compile
software. This variable lists any and all that are essential to this task.
For example, if your distro packages are squashfs files, then one of the
items in this list should be 'squashfs-tools'. There is a complimentary
variable in the other config file where packages specific to that software
can be defined.


.B EXT_BLDR
[tgz file] The file extension used for the package builder profile. These
values can utilize any of the naming variables listed at the top of this
section and should be enclosed with single quotes (').

.B EXT_CODE
[tgz file] The file extension used for a package source code

.B EXT_DEPS
[text file] The file extension used for the package dependency list

.B EXT_HASH
[text file] The file extension used for the package validation hash

.B EXT_INFO
[text file] The file extension used for the package details info

.B EXT_LIST
[text file] The file extension used for the package manifest info

.B EXT_MAKE
[text file] The file extension used for the package make commands

.B EXT_SOFT
[mksquashfs file] The file extension of the actual packaged software


.B NAME_SFX
An optional suffix to apply to the packages names when using '-b package'.
Typically this would be '-${TYPE}' to designate the different types of
package files.

.B NAME_BIN
Used in conjunction with NAME_SFX, this value is a boolean (true/false)
that indicates whether NAME_SFX should be applied to binary packages,
which is usually no (blank value).


.B OWN_USER
If the software is simply being compiled (using the -c action), then this
value will be ignored. When a distributable package is being created, this
is used to apply that ownership to the files and directories. This value
can be either usernames or their numeric equivalents. Although this will
be applied to everything in the package, finite modifications of ownership
can be applied using the 'pre.package' script.

.B OWN_GROUP
Like the OWN_USER, this is also part of the ownership of the data within
the packages, but for group ownership.


.B PRM_DIRS
Working in conjunction with the OWN_* values, these three provide the
permissions that get applied to various parts of the package. In this
case, the value here gets applied to all the directories. The value can be
in numeric form (using three or four digits) or using symbols (e.g. u+rX).
Specific modifications can also be implemented using the 'pre.package'
script.

.B PRM_EXECS
The permissions for binaries/executables

.B PRM_FILES
The permissions for all other files


.B URL_INFO
In order for builder to perform some of its steps, it needs access to the
proper information. Some of this information can be stored in a .info file
created by a Linux distribution. This variable stores the URL to that file
so it can be downloaded and processed by builder. These two values can
utilize any of the naming variables listed at the top of this section and
should be enclosed with single quotes (').

.B URL_REPO
This URL should point to the package source code for the Linux distro.


.B SPM_ALL
Working with the DEP_MAKE_ALL variable, this one stores the actual command
to install the packages listed. The DEP_MAKE_ALL variable needs to be part
of this value.

.B SPM_PACK
Like SPM_ALL, this variable is also responsible for the installation of
dependencies. However, this one works with the DEP_MAKE_PAK value defined
in the builder profile 'config' file.

.B SPM_DEPS
The final variable associated with the installation of dependencies, this
one is the command to install a package after it was built due to it being
a dependency for another package in a multi-pass build. This one uses the
DEPS variable value defined in the profile config[.#] files.

.B SPM_MAKE
The command listed for this variable needs to be all the commands required
to create the package file(s). There are several variables available for
use with this command:
  ${ID}       - directory or package name (depending on the configuration)
  ${TYPE}     - package type (e.g. bin, doc, drv, etc)
  ${PAK_DEPS} - the interpreted package deps file extension
  ${PAK_HASH} - the interpreted package hash file extension
  ${PAK_INFO} - the interpreted package info file extension
  ${PAK_LIST} - the interpreted package list file extension
  ${PAK_SOFT} - the interpreted package soft file extension

.B SPM_UNLD
To maintain a tidy environment, include the command to unload the packages
listed in the DEP_MAKE_ALL and/or DEP_MAKE_PAK variables. A blank value
disables this process.


.B LOG
The log file for all executions of builder


.B SUDO
Depending on the account used to run builder, the use of sudo may be
required to perform an installation, or ownership and permission change of
the files when packaging. If the executing account does not have sufficent
privileges, you can set this value to 'TRUE'. If you require switches to
be passed to sudo, you can also list them here (e.g. SUDO='sudo -x -y -z).


.B PATH_PKGCFG
This directory contains temp files used by the software.


.B FLAG_A32
These are the compile flags for ARM 32bit CPU architectures

.B FLAG_A64
These are the compile flags for ARM 64bit CPU architectures

.B FLAG_I32
These are the compile flags for Intel/AMD 32bit CPU architectures

.B FLAG_I64
These are the compile flags for Intel/AMD 64bit CPU architectures

.B FLAG_R32
These are the compile flags for Raspberry Pi 32bit CPU architectures

.B FLAG_R64
These are the compile flags for Raspberry Pi 64bit CPU architectures

NOTE: the above flags can be universally set in the main config file, with
per-instance adjustments made in the builder profile config. These values
can also incorporate any of the special variables outlined at the top of
this section, as well as PATH_PKGCFG.

This configuration file can also contain all the variables in the below
section that begin with DIR_ and CFG_, and will act at the defaults.




.I Profile Config

Each of these variables can also be defined in the global config as the
default values used, with the ones in this file being specific instances
where deviation is required. It is important to note that these values
should include the DIR_INST variable so that any desired directory prefix
can be applied to the installation path (e.g. /usr/local). You may notice
that some variables begin with DIR_ while others begin with CFG_. The two
differenciate only in that the CFG_ variables are passed to the configure
script during compilation, whereas the DIR_ are used in other places. Both
however, can be used at any time.

.B DIR_INST
If this value is different than the default, which is usually root (/),
then you can specify an alternate directory where the package contents
will reside in the running system (typicall '/usr/local')

.B DIR_DEVMAN
The directory used to store device manager rules/scripts

.B DIR_MARKERS
The directory used to store installed package (cache) data

.B DIR_SCRIPTS
The directory used to store service start/stop scripts


.B CFG_BIN="${DIR_INST}/bin"
The directory location for general use binaries

.B CFG_DATA="${DIR_INST}/share"
The directory location for common use files

.B CFG_DATAROOT="${CFG_DATA}"
The directory location for common use files

.B CFG_DOC="${CFG_DATA}/doc/${NAME}"
The directory location for documentation files

.B CFG_DVI="${CFG_DOC}"
The directory location for print related files

.B CFG_HTML="${CFG_DOC}"
The directory location for HTML-based doc files

.B CFG_INCLUDE="${DIR_INST}/include"
The directory location for compiling header files

.B CFG_INFO="${CFG_DATA}/info"
The directory location for documentation files

.B CFG_LIB="${DIR_INST}/lib"
The directory location for common use libraries

.B CFG_LIBEXEC="${DIR_INST}/libexec"
The directory location for executable libraries

.B CFG_LOCALE="${CFG_DATA}/locale"
The directory location for region specific files

.B CFG_LOCALSTATE="${DIR_INST}/var"
The directory location for variable data files

.B CFG_MAN="${CFG_DATA}/man"
The directory location for documentation files

.B CFG_OLDINCLUDE="${DIR_INST}/include"
The directory location for compiling header files

.B CFG_PDF="${CFG_DOC}"
The directory location for documentation files

.B CFG_PS="${CFG_DOC}"
The directory location for documentation files

.B CFG_SBIN="${DIR_INST}/sbin"
The directory location for elevated privileged binaries

.B CFG_SHAREDSTATE="${DIR_INST}/com"
The directory location for shared state files

.B CFG_SYSCONFIG="${DIR_INST}/etc"
The directory location for software configurations

.B CFG_MISC
This variable is unique to the builder profile config only, NOT the global
configuration! This value gets added to the 'configure' call so this value
needs to have its switch included. For example, mplayer has a non-standard
switch to place its codecs. Simply add "--codec-dir='/whatever/dir'" for
this variable value to use it.


The variables below are specific to the builder profile config file and
define various aspects for the individual software.

.B CHECK
Indicates that a 'make check' command needs to be run; 0=no, 1=yes

.B CLEAN
Indicates that a 'make clean' command needs to be run. A value of '2' indicates
that a 'make distclean' needs to be run instead; 0=no, 1=yes, 2=yes

.B CONF
Indicates that a 'configure' command needs to be run; 0=no, 1=yes

.B PROP
Indicates that a 'make mrproper' command needs to be run; 0=no, 1=yes

.B TEST
Indicates that a 'make test' command needs to be run; 0=no, 1=yes

.B DEPS
Indicates that the package that was just built is a dependency for another
package in an upcoming pass (in a multi-pass builder call). This value
would need to be the name of the generated package (since it can vary
depending on the configuration parameters). For example, if alsa is being
compiled collectively, the first package needs to be the 'lib' so it can
be installed to build the 'bin' package afterwards. Therefore, the value
in config.1 could be 'alsa-lib.tcz' (if that matches your package naming
convention). A more dynamic value would be '${PACKAGE}${EXT_SOFT}' which
allows for general naming, but may not satisfy every build.

.B SORT
Indicates the package contents need sorting (on this pass); a blank value
means no, any other value means yes.

.B CODE
This variable is optional and should only be used when compiling more than
one software with a single builder profile. For example you can compile
both alsa-libs and alsa-utils with a single 'builder -b alsa' command if
the config.1 file CODE value is 'alsa-libs' and config.2 file CODE value
is 'alsa-utils'. This value would uniquely identify which source code
directory to use per pass.


.B GIT_REPO
The URL to the developers source code located in a git repo. This value is
optional, but does allow '-C git' to be passed. If the software requires a
multi-pass, this needs to be in the config.1 file since the source needs
to be downloaded in the first pass.

.B URL_CODE
Same as above, but the URL to a non-git (homepage) download link, allowing
a '-C dev' to be passed. To make this easier, it is recommended to use a
constant name for this value (e.g. domain.com/software/latest|stable).
Obviously this would be up to the software author to institute such a
naming convention.


.B CUSTOM
If the compile type is 'custom', you need to specify all commands here.
For example: gcc -O foo
This variable can contain any of the special variables outlined in the top
of this section. Just be sure to surround it with single quotes when doing
so!


.B DEP_MAKE_PAK
Most software needs one or more dependencies installed in order to compile
successfully. Use this variable to list each that are required (separated
using a single space).


.B DEP_EXEC_BIN
When creating multiple distributable files (versus creating a single file)
for a particular software title, this variable will store each dependency
for the binaries package. The values for each of these variables needs to
be a space separated list of names.
If a single distributable package is desired, each of these variables will
be added to the .deps file to have the complete run-time list required for
any aspect of the package to function properly.

.B DEP_EXEC_DEV
Like DEP_EXEC_BIN, this package stores the development headers for this
software. This value needs to store any dependencies for this package.

.B DEP_EXEC_GIR
Just like the two above, the list here needs to pertain to the gir files
package.

.B DEP_EXEC_LIB
Lastly, this variable holds the dependency list for the shared libraries
package.


.B FLAG_CONF
Used in conjunction with the CFG_* variables outlined above, this value
should store any additional parameters you wish to pass to 'configure'.
Typically this will just be the '--prefix' switch, but can be any valid
option that is desired.

.B FLAG_MAKE
This variable does the same as FLAG_CONF, but is passed to 'make'.
Typically this will just be the 'DESTDIR' value, but can be any valid
option that is desired.

.B FLAG_INST
Sharing the same function as the above two, this value gets passed to the
'make install' call.

NOTE: the FLAG_* variables outlined above for the various CPU achitectures
can be added in this file also. See the appropriate section above for more
information.




.I Parameters File

.B ARCH
Specifying a value here is the equivalent to passing the '-A' option. By
default this value is 'i64'.

.B DIRS
Using this variable is the same as passing the '-D' option. The default is
to use the passed NAME parameter instead of the directory names, leaving
this value blank. See the OPTIONS section below for more information.

.B INFOFILE
This variable can be used in conjunction with the SOURCE counterpart below
and would act like -I was passed. If SOURCE has a value, this one should
be set to TRUE as well so that the source code can be obtained from the
proper location (unless SOURCE='dir'). The default value is blank.

.B PASS
Indicating how many passes should be used with the profile, this is the
same as passing the '-N' option. The value here should be a number that
is 1 or greater, with a default of 1.

.B SKIP
To skip packaging the files until the final pass, this value is the same
as passing the '-F' option. The default is to leave this blank. Please
note that providing a value here also needs one for the PASS variable
above.

.B TRIM
Having a bit more complexity than the other variables in this file, this
one allows you to use regular expressions to trim a portion of the NAME
parameter, and is the equivalent of passing the '-R' option. The default
value is blank.

.B METHOD
Relating to the compilation method (-M), this variable needs to be one of
the valid word values instead of a simple binary. The default here is the
standard 'configure, make, make install'.

.B SOURCE
Finally, this variable corresponds to the '-C' option that specifies the
location to download the source code from. There is no default value.

You may have noticed that the -{PSTU} options do not have representation
in this file. Both of those switches should not affect the outcome of the
software compilation, and should be left to the user to apply them if
desired.




.SH PARAMETERS

There are at least two parameters that are necessary to start a task
successfully - an ACTION and a NAME. The only exception to providing a
NAME value is when using the '-t' action, which just creates a blank
template for any project. Otherwise, the NAME is used to identify which
directory to enter, which builder profile to use, etc. There are also
OPTIONS that can be used to modify execution behavior.

The last parameter builder can accept is DIRECTORY. It operates as the
location for the passed action, and is optional. To provide flexibility
for the user, there are several different syntaxes that are permitted.
Both full and relative paths are permissible, but the value must contain
a forward slash (/) to indicate it's a directory instead of a package
name. This will not be a problem with full paths as they obviously start
with one. Relative paths can either begin with a './', end with a '/',
or contain a slash within the value (e.g. 'some/dir').

To summarize, the DIRECTORY value can be:
  o A full path: /dir/builder/
  o Or a relative path: ./builder
    Containing a slash: dir/builder
    With a trailing slash: builder/




.SH ACTIONS

As with virtually all software, switches can be passed to modify its
operation. The below section covers each switch in detail, separating
the actions from the options. It is important to note that the options
actually need to proceed the actions when calling builder.

.B --help
Shows helpful information about the program

.B --version
Displays the software version and exits.

.B -b VALUE
The most frequently used action. This builds software from source code
and either installs it into your running system (via the 'install' value),
or creates a distributable package for your Linux disto (using 'package').
If DIRECTORY is passed, that will be the location used to process the
source code.

.B -c
After you have created a builder profile template and filled it out, you
can use this action to create a single file for distribution. Ideally the
software author would create a generic profile to make it easier for
package maintainers for the various Linux distros to quickly modify to fit
their own environment. An alternative location can be specified to package
using the DIRECTORY parameter, otherwise a directory matching the NAME
value in the current location will be used.

.B -d
Before builder can process a projects source code, it needs to acquire its
profile first. This action will instruct builder to download the file to
your device using the Linux distro repository defined with the URL_REPO
value in the global config file. While it's not possible to chain ACTIONS,
there is an exception for this one and '-i' so the two can be combined
into a single call. The DIRECTORY value will indicate the location that
the profile will be downloaded into.

.B -i
If you already obtained a builder profile from a non-distro repo source,
then you can use this action to install it. As mentioned above, this can
also be chained with the '-d' action in a single command to execute both
tasks just one call. The DIRECTORY parameter will be used as the source
location storing the builder profile.

.B -r
While not a routine task, there may be times when it is useful to update a
package with alternative or additional files, without having to recompile
everything. This would most likely be used between distros that are forks
of others and have slight modifications. You may also find this useful if
package separation is desired (e.g. binaries, libraries, documentation).
Use the DIRECTORY parameter to indicate the location to re-package,
otherwise a directory matching the NAME value in the current location will
be used.

.B -t VALUE
Use this action to create a builder profile template. This maintains a
uniform layout, and makes it easier to know what to configure and include.
There are three values that can be used to create different parts of the
entire template. Passing 'info' will simply generate a sample .info file,
whereas 'profile' will create an example builder profile. To make both of
these in a single call, pass the 'all' value. By default this places the
files in a 'template' directory under DIR_TEMP, but can be changed using
the DIRECTORY parameter.

.B -u
As time passes, builder profiles will need to be updated. This could be
due to a different compilation method for the software, or by some other
change that made the prior profile obsolete. By default, builder will not
overwrite an installed profile. This action will uninstall an existing
profile so that a new one can be added.




.SH OPTIONS

To adjust the behavior of actions, you can pass one or more options when
executing builder. Remember that these actually need to proceed the action
switch!

.B -A VALUE
Specifies an alternative CPU architecture to process. This could be useful
for mixed 32/64 bit environments, or for building software for a different
target device. Presently the supported processors (both 32 and 64bit) are:
ARM, Intel/AMD, MIPS, PowerPC, Raspberry Pi (also ARM), RISC-V. Contact
our staff to add others in future updates.

.B -C VALUE
This switch identifies where the source code for the software should be
obtained from (unless it was already downloaded manually). There are
multiple supported locations to make sure at least one is available. None
are mandatory, but at least one should be listed so builder can perform
this step for the user if they invoke this switch.

The first value is 'dev' and belongs to the official software author. This
would typically be their homepage download link but it can be any official
location containing their source code in the absense of a website. The two
values used in the .info file are 'homepage' and 'download', which will be
appended to one another.

The next value is 'dir' and can be used if you already have an existing
copy of the source code. It needs to be a compressed file (tbz, tgz, zip)
and specified using the DIRECTORY parameter that also includes the name of
the file as well.

The third value is 'git', which can pull the source code down from an the
online git repo specified in the .info file. Since this uses git, make
sure that it is installed before running builder with this value. There
are actually three values that can be used from the .info file: git, file,
and clone. The latter two are appended to the 'git' URL, so either or both
can be specified for flexibility (with the 'file' taking precedence).

The final value for this variable is 'repo'. This location utilizes the
URL of your Linux distro repo to obtain the source code. The two values
used in the .info file are 'repo' and 'source'. Like the others, they are
combined to produce the entire URL to acquire the proper file.

To summarize, the VALUE can be:
  dev  [URL_CODE]: the software authors official download link
  dir  [DIR_REPO]: a directory containing existing source code
  git  [GIT_REPO]: an online git repository containing the code
  repo [URL_REPO]: the Linux distro repo URL storing the code

.B -D
Most of the time the passed NAME parameter is used to name the package,
however, there are some software that multiple packages get created from.
An example is php, which can sometimes get separated into: php, php-cli,
php-fpm, etc. In this situation, the -D switch provides the mechanism to
use alternative names when creating the packages. To use this method, a
post.compile[.#] script will need to create and move the appropriate files
into each directory. Be aware that the individual package separation will
still take place and generate packages like php-cli-doc, php-cli-lib, etc,
so make sure to place all the proper files into each directory. If there
is a builder profile installed, you should not use this option without any
modifications to the post.compile[.#] script mentioned above.

.B -F
When creating packages, more often than not, the packaging should be done
at the end of the (final) pass. There may be a rare exception to this rule
and this step should take place beforehand. Issuing this option will make
the making process occur before the final pass. Although this probably
would not occur, there may be undesired results if this switch is used
when -N is greater than 2. If there is such an instance, reach out to our
staff to resolve this matter. Do not use this option if a builder profile
is installed, without making modifications to it.

.B -I
The .info file contains a plethora of information. This option works in
conjunction with '-C' to find the source code for the software, with the
only exception being '-C dir' (which uses DIR_REPO). If this option is
not passed, then the necessary information is gathered from the builder
profile of the software itself. This switch is defined with the URL_INFO
value in the global config file.

.B -M VALUE
To help make it easier in building a profile, several common methods of
compiling have been added, which include: autoconf, autogen, bootstrap,
cmake, default (configure, make, make install), and scons. To provide
flexibility to the developer, there is one other option that is aptly
named 'custom'. Using that value will require all the calls necessary to
compile the software stored in the CUSTOM variable of the profile. To use
this option without a builder profile, you will need to export the
variable before making the call to builder:
   export CUSTOM='step 1; step 2; ...'; builder ...
Do not use this option if a builder profile is installed, without making
modifications to it.

.B -N VALUE
Some software require more than one pass to compile. In that instance you
can pass this option along with a number for its value to indicate how
many passes should be performed. It's important to note that when using
this switch, all the profile files (and directories) will need to have a
number appended to them to designate which pass they need to be applied
(e.g. config will need to become config.1, config.2, etc). Do not use this
option if a builder profile is installed.

.B -P
There may be instances when you want to compile software without including
any accompanying patches. For instance, some Linux distros occasionally
create patches to meet certain needs or requirements for their working
environment. This switch will prevent all of them from being applied
during the compilation process. To perform this action, the patches will
obviously need to be included in the 'patches[.#]' directory of the
builder profile.

.B -R VALUE
Although rare, there may be times when the package name needs adjustment.
This option will enable you to remove a portion of the package name, with
optional use of RegEx anchors in the value. For example, lets take the
libmount package and adjust it so it becomes mount-lib. By simply passing
'^lib' with this option, the 'lib' prefix will be removed while retaining
the 'mount' portion of the name. Since the files compiled will all be libs
the package will automatically have the '-lib' suffix applied based on the
EXT_SOFT config value.

.B -S
Instead of separating the files into different package types (e.g. bin,
lib, doc), some Linux distros may prefer to bundle all the contents into a
a single file. Use this option to perform that step.

.B -T VALUE
When obtaining various files from a distro repo, you may need to specify
which file type is being sought. This option allows you to obtain the
desired file.

.B -U
Whether testing a profile before finalizing the configuration, or you're a
package maintainer that needs to compile multiple software, this option
prevents the essential compilation packages (listed in DEP_MAKE_ALL) from
getting uninstalled after a successful run of builder. Otherwise, to keep
the system tidy, those packages will be removed afterwards.




.SH INFO FILE

The .info file contains a plethora of information related to the software,
but only has meaning to builder to obtain the source code. In that respect
this file is used as an alternative to a builder profile. Below we will
cover each field with the value and an example in brackets.

.B name [tar]
This line obviously deals with the actual name of the software itself, and
should correspond with the package name.

.B title [Archive Manager]
Using two or three words, this should indicate a title for the software.

.B description [Manages various compressed file types]
A short description of what the software actually does.

.B version [1.2.3]
Obviously this defines which software version this file pertains to

.B released [2026.03.04]
The date that the software version was released

.B packaged [2026.03.05]
The date that the software was turned into a package for the Linux distro

.B authors [Tim, Bill, Paul]
A comma separated list of developers for the software. Alternatively, this
value can contain a single person per line, with a preceeding and trailing
set of dashes:
   authors:	-----
		Author 1 <name@domain.com>
		Author 2 <name@domain.com>
		...
		-----

.B homepage [https://www.company.com]
The homepage URL for the software project

.B download [path/to/file/filename.tgz]
The remaining portion of the homepage URL to complete the download link.
If the URL is completely different from the homepage value, then list the
entire value here. This can be an alternate to the git and repo options.

.B git [https://distributor.com/path/to/project]
If an online git repo is used, this would be the URL to the project

.B commit [path/to/commit/abcd...wxyz]
The remaining portion of the git URL to access the commit notes for the
project. This is similar to the version line above to indicate the last
commit included in this release.

.B file [path/to/file/filename.tgz]
The remaining portion of the git URL to download a pre-packaged source
code file. This can be an alternate to the homepage and repo options.

.B clone [.git]
The remaining portion of the git URL to clone a repo locally. This can be
an alternate to the homepage and repo options.

.B repo [http://distro.com/path/to/repo]
The Linux distro repo URL

.B package [tar-1.2.3.deb]
The remaining portion of the repo URL to download the pre-compiled software

.B source [tar-1.2.3.dsc]
The remaining portion of the repo URL to download the (unpatched) source
code. This can be an alternate to the homepage and git options.

.B builder [tar-1.2.3.bldr]
The remaining portion of the repo URL to download the customized builder
profile for the specific Linux distro. Any specific software patches can
be added in this file.

.B compile [tar-1.2.3.make]
The remaining portion of the repo URL to download a single script to
compile the software. This is not related to builder, but may be an option
for users as an alternative.

.B size [100K]
The package size (in kilobytes)

.B installed [150K]
The installed software size (in kilobytes)

.B category [utilities]
The category that this software belongs to. This list varies by distro,
but a reasonable list might include:
education|games|multimedia|productivity|social|system|utilities

.B interface [cli]
Defines the software interface: cli|gui

.B toolkit [none]
Defines the toolkit/language used. This field is not applicable for some
software such as libraries, in which case 'none' should be used. Where
applicable, some examples include:
[CLI] shell|lua|ruby|php|python|tcl|tk|...
[GUI] fltk|gtk|html|qt|wxWidgets|...

.B rating [g]
The age restriction placed on the software. This would deal more with
games and educational software, while most everything else would have a
'g' value here.	This mirrors the MPA ratings: g|pg|pg-13|nc-17|r

.B license [LGPLv2.1]
The software license that the software is released under

.B document [https://www.gnu.org/licenses/lgpl-2.1.en.html]
The URL to an online copy of the license document

.B maintainer [cat_eyes, pedro]
The comma separated list of names to maintain the package

.B tags [archive manager tar tarball compressed uncompressed ...]
The space separated project keywords

.B overview [tar is an archive manager that has existed since the 70's...]
This is a detailed overview for the project, and can span paragraphs

.B comments [This version is compiled without XZY support.]
Any applicable comments for the package

.B changes [Updated to the latest version]
Brief list of changes between package releases





.SH EXAMPLES

The below list shows various examples for using builder. This list is not
exhaustive and does not indicate modifications using any options.

Download a builder profile from your Linux distro repo:
     builder -d tar [DIRECTORY]
Install a (manually) downloaded builder profile:
     builder -i tar [DIRECTORY]
  NOTE: the above two steps can be combined:
     builder -d -i tar [DIRECTORY]

After the installation of a builder profile, the software can be compiled
or packaged.

Compile and install software:
     builder -c tar
Compile and create a distro package:
     builder -b tar

For software developers that want to create a generic builder profile for
their project, builder can make templates. If a profile is not available
from the software author, package maintainers can perform the following
steps to create one for their specific Linux distro.

Create a .info file template:
     builder -t info myproject [DIRECTORY]
Create a profile template:
     builder -t profile myproject [DIRECTORY]
  NOTE: the above two steps can be combined:
     builder -t all myproject [DIRECTORY]
Create a distributable profile after the above two steps:
     builder -p myproject [DIRECTORY]




.SH BUGS

There are no known bugs as of March 2026.

Please visit our website for the latest list of opened bug reports for
this software project - http://www.cliquesoft.org.



.SH COPYRIGHT

Copyright (C) 2017-2026 Cliquesoft

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.




.SH AUTHORS

Dave Henderson

